dataset: "clevrer"
num_slots: 7
slot_dim: 128
num_heads: 4
qkv_size: 128
mlp_size: 256
num_layers: 2
h_layers: 1
out_mlp: false
out_hidden_layers: 1
integrator_method: "Leapfrog"
delta_t: 0.125
burnin_frames: 6
rollout_frames: 10
batch_size: 32
learning_rate: 2e-4
num_epochs: 50
lambda: 1.0
max_grad_norm: 0.05
warmup_steps: 2500
weight_decay: 0