dataset: "clevrer"
num_slots: 7
slot_dim: 128
burnin_frames: 6
batch_size: 64
learning_rate: 2e-4
num_epochs: 21
encoder_backbone: "cnn"
encoder_features: [32, 32, 32, 32]
corrector_iterations: 1
broadcast_size: [8, 8]
decoder_features: [64, 64, 64, 64]
targets: {"video": 3}
max_grad_norm: 0.05
warmup_steps: 2500