dataset: "realworld"
num_slots: 6
slot_dim: 192
burnin_frames: 6
batch_size: 24
learning_rate: 2e-4
num_epochs: 46
encoder_backbone: "resnet18"
encoder_features: [64, 128, 256, 512]
corrector_iterations: 1
broadcast_size: [12, 7]
decoder_features: [64, 64, 64, 64]
targets: {"video": 3}
max_grad_norm: 0.05
warmup_steps: 2500